env: "prod" #local, dev, prod
dsn: "postgres://<username>:<password>@localhost:5432/<db_name>"
http_server:
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 60s
  user: myUser
  password: myPass